### PR TITLE
Updated schedule to include application area talks

### PR DESCRIPTION
**Pull request by cjvogl**
@rjleveque, how does this schedule look?

### CODE REVIEW

**Comment by mandli** [comment]
Can you push this to the web for ease of viewing?

**Comment by cjvogl** [comment]
Sure: http://faculty.washington.edu/cvogl/clawdev-2016/index.html

**Comment by rjleveque** [comment]
Looks good to me, except Dave George's talk should start at 10:10.

Thanks!

**Comment by cjvogl** [comment]
Thanks for catching that!

**Pull request merged**
